### ISSUE TITLE
有时候ListView拉倒底部并没有刷新

### ISSUE THREAD

**Issue by soliury** [soliury/noder-react-native#1]

**Comment by soliury** [comment]
It's a bug of React Native

**Comment by alsotang** [comment]
竟然。。

2015-07-11 2:45 GMT+08:00 soliury <notifications@github.com>:

**Comment by soliury** [comment]
一个很奇怪的bug，我修改了一下源码，但是没有一个很好地解决办法

**Comment by soliury** [comment]
此问题已解决，因为listview的滑动到底部的触发事件在同一个高度只会触发一次，然后我loading渲染放到了footer里面，也就是listview里面，所以高度一直变动，这个问题就迎刃而解了
