### ISSUE TITLE
[install]导入xcode出现错误，怎么解决？

### ISSUE THREAD

**Issue by TakWolf** [soliury/noder-react-native#10]
![6aad1e84-de01-4c8b-964d-f6deef25e26f](https://cloud.githubusercontent.com/assets/6064962/9003277/26b5ca3c-379f-11e5-8d02-ff4a60a82155.png)

XCode版本是 6.4

**Comment by TakWolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6064962/9003304/5ceb4a32-379f-11e5-936f-e182bd73fe80.png)

这一步没懂，是这个原因吗

**Comment by soliury** [comment]
不是，重新安装吧，是缺文件。依赖的文件。。。

**Comment by TakWolf** [comment]
重新安装npm问题还是没解决
xcode程序启动的时候跳出控制台，提升如下错误

![image](https://cloud.githubusercontent.com/assets/6064962/9003397/51249298-37a0-11e5-9f8d-235dc99bec37.png)

**Comment by soliury** [comment]
缺少东西，安这个来，先把需要的工具安装了：http://facebook.github.io/react-native/docs/getting-started.html

**Comment by soliury** [comment]
```
brew install watchman
brew install flow
```

**Comment by TakWolf** [comment]
懂了，我脑残了。。。

**Comment by soliury** [comment]
ok, 有问题再说，对了，你咋也开始研究react-native了

**Comment by TakWolf** [comment]
我无聊逛nodecn看到你发了，down下来研究一下
万一好用呢

**Comment by soliury** [comment]
还行，不过性能是问题，listview的性能限制了发展

**Comment by TakWolf** [comment]
还是没成功
![image](https://cloud.githubusercontent.com/assets/6064962/9004522/48168266-37a9-11e5-8f58-fc9a0ef4eca1.png)

![image](https://cloud.githubusercontent.com/assets/6064962/9004527/528df760-37a9-11e5-8028-e97c28859781.png)

我改装的都安装了，安装官方文档创建Hello World可以运行

**Comment by soliury** [comment]
需要啊，但是我package里标明了。
你这个问题，应该是react-native-modal这个库的oc文件缺了，你去node_modules里看看，缺了，自己从别的地方拷贝过来就行。

**Comment by soliury** [comment]
这个是因为react-native-modal库依赖react-native-blur，应该是在modal库中依赖的blur库的oc代码没有全，你需要自己去clone下来拷贝过去，但是我没有遇到这个问题，你却遇到了。我曾经试过，删除node_modules重新安装都行得。

**Comment by TakWolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6064962/9005133/2c590738-37ae-11e5-9011-00f94e8c71d0.png)

这两个是吗

**Comment by soliury** [comment]
对对，如果modal里的oc文件缺了，你可以去blur中复制过来，或者，最好的方式，是在xcode中，你去modal中，看到有些文件是变红得，就是xcode包含了，但是，实际找不到文件，你可以直接添加。

**Comment by soliury** [comment]
```
cd node_modules/react-native-modal
sudo npm install
```

**Comment by TakWolf** [comment]
实际文件是存在的。
![image](https://cloud.githubusercontent.com/assets/6064962/9005223/fa00318e-37ae-11e5-9434-4b3f6f37cbc2.png)

![image](https://cloud.githubusercontent.com/assets/6064962/9005241/165b8dd8-37af-11e5-8e3d-bb22c132d5eb.png)

是xcode找不到了吗？

**Comment by soliury** [comment]
应该不是，这个问题，容我想想。。。。
去xcode中，运行按钮的右边，有一个选择，你选择react，然后comm+b，试试会不会报错

**Comment by soliury** [comment]
或者，在xcode Libraries中，删除React库，然后右键，添加文件，添加node_modules/react-native/React.xcodeproj

**Comment by TakWolf** [comment]
可以运行了 = =！
![image](https://cloud.githubusercontent.com/assets/6064962/9005306/ad7ee386-37af-11e5-8df8-0793b7714e56.png)

果然是这一句我没搞懂。。。
先要编译react

**Comment by soliury** [comment]
哈哈，

**Comment by TakWolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6064962/9005332/f0e70d06-37af-11e5-9507-dfce82a1dac3.png)

这一步我也执行了

![image](https://cloud.githubusercontent.com/assets/6064962/9005344/0538793e-37b0-11e5-96e8-809b318cf0aa.png)

原来目录中是没有react-native-blur的

可能和这个也有关系

**Comment by soliury** [comment]
对对，当然有关系，这个modal中用到了，blur库，我虽然全局下也安装了blur但是，modal下没有blur的话，oc会出错，如果全局下没有blur的话，js会出错。

**Comment by soliury** [comment]
主要是，我项目用到了modal，modal又引用了blur，而且项目中又要直接使用blur。这关系有点复杂。

**Comment by TakWolf** [comment]
大概get了

**Comment by soliury** [comment]
怎么样，跑起来感觉咋样，要不，等安卓出来了，你也帮忙开发一下noder的安卓版嘛？

**Comment by TakWolf** [comment]
还有个小问题，xcode中有这样一个文件
![image](https://cloud.githubusercontent.com/assets/6064962/9005538/9f99ca04-37b1-11e5-887c-8c938c30bd4a.png)

![image](https://cloud.githubusercontent.com/assets/6064962/9005557/c45283f4-37b1-11e5-84e1-47163a1de300.png)

提示找不到路径

**Comment by soliury** [comment]
哦哦，你需要：

```
react-native bundle
```

**Comment by soliury** [comment]
因为这个是编译后产生的文件，所以我加入了gitignore

**Comment by TakWolf** [comment]
需要修改ip是吗，在哪里修改

![image](https://cloud.githubusercontent.com/assets/6064962/9005757/68e9fa7c-37b3-11e5-8357-198e5daa7011.png)

**Comment by TakWolf** [comment]
发现nodecn好像并没有android客户端

**Comment by soliury** [comment]
是的，运行`npm start`，你得注意看文档啊，我都写了。

**Comment by TakWolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6064962/9005785/cc19652e-37b3-11e5-92db-368a0b263a65.png)

android端说是10月份开源

**Comment by TakWolf** [comment]
效果很不错，赞一个！
ListView能感受出

**Comment by soliury** [comment]
哈哈，是的，十月份开源。
