### ISSUE TITLE
WARNING in ./~/react-native-html-render/lib/htmlparser2.js Critical dependencies: 26:39-47 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.  @ ./~/react-native-html-render/lib/htmlparser2.js 26:39-47 webpack: Compiled with warnings.

### ISSUE THREAD

**Issue by zhushichuan** [soliury/noder-react-native#100]
WARNING in ./~/react-native-html-render/lib/htmlparser2.js
Critical dependencies:
26:39-47 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-native-html-render/lib/htmlparser2.js 26:39-47
webpack: Compiled with warnings.

**Comment by flyskywhy** [comment]
这只是警告一下 react-native-html-render/lib/htmlparser2.js 是已经被比如 webpack 预编译过的，再次被 webpack 时提醒一下而已
