### ISSUE TITLE
react-native bundle后报错

### ISSUE THREAD

**Issue by lys623** [soliury/noder-react-native#11]
<img width="818" alt="2015-08-07 10 08 02" src="https://cloud.githubusercontent.com/assets/4364314/9127376/ac55a8cc-3cec-11e5-8203-862195b75166.png">

**Comment by soliury** [comment]
这些是正常的吧，也能运行就行。

**Comment by huanglong** [comment]
理论上应该不影响，我下载下来，跑一遍，感觉是有点问题：

![image](https://cloud.githubusercontent.com/assets/670360/9457835/b133fcd2-4b19-11e5-8457-dc0e4388d927.png)

**Comment by soliury** [comment]
这个问题，重新安装。。。缺少文件。。

**Comment by huanglong** [comment]
是的，npm install 会漏掉这个

**Comment by soliury** [comment]
现在能运行吧

**Comment by huanglong** [comment]
可以的，解决方案是：

1. 进入到 node_modules/react-native-modal/ 下，手动 install 一下 react-native-blur
2. 通过 brew update 和 upgrade 下 watchman 和 flow

**Comment by soliury** [comment]
OK, thank you .
