### ISSUE TITLE
user.avatar_url 返回值更新

### ISSUE THREAD

**Issue by alsotang** [soliury/noder-react-native#13]
这个 avatar_url 有更新，之前返回的是 `/agent?url=xxxx` 的地址，现在服务器准备回到国内，所以不再具备代理能力。之后这里会直接返回 `url=xxxx` 的真实url

**Comment by soliury** [comment]
直接返回url值不行么？
就是avatar_url=xxx

**Comment by alsotang** [comment]
现在就是直接返回 url 值了，你看看。https://cnodejs.org/api/v1/user/alsotang

2015-08-12 12:10 GMT+08:00 soliury <notifications@github.com>:

**Comment by soliury** [comment]
ok, I see

**Comment by soliury** [comment]
已完成
