### ISSUE TITLE
Xcode Run时报错

### ISSUE THREAD

**Issue by ForeverPx** [soliury/noder-react-native#14]
![image](https://cloud.githubusercontent.com/assets/7984208/9811397/9c4c3620-58a9-11e5-844f-bf0ebaa8917d.png)

情况如上图。。求解决方案

**Comment by soliury** [comment]
这样吧，重新安装react-native-icons，然后再点击运行按钮右边的选择框，选择ReactNativeIcons，然后comm+R编译它。

**Comment by ForeverPx** [comment]
重新装了react-native-icons，然后编译的时候还是报同样的错误

**Comment by soliury** [comment]
你安装的是哪个版本的react-native-icons？

**Comment by ForeverPx** [comment]
0.3.4

**Comment by soliury** [comment]
安装 "react-native-icons": "0.3.4"，安装0.3.4版本，不然会出错

**Comment by soliury** [comment]
你确定是么，用npm outdate看看

**Comment by soliury** [comment]
最好是这样做，
```
cd node_modules/react-native-icons
sudo npm install
```

**Comment by ForeverPx** [comment]
sorry, 确实 0.3.4不会报错，谢谢。
不过还有个问题：
![image](https://cloud.githubusercontent.com/assets/7984208/9811998/077634f2-58ad-11e5-8e48-3fa2d455b7d9.png)

**Comment by soliury** [comment]
这个问题是blur的问题，重新安装，重新编译

**Comment by soliury** [comment]
我想应该没有问题了吧，我把这个issue关了
