### ISSUE TITLE
Upgrade for React Native 0.11.0

### ISSUE THREAD

**Issue by jsierles** [soliury/noder-react-native#15]
On the React Native Playground, we've retired versions before 0.11.0, so I had to remove this example from the front page which is not working there anymore. But, it would be great to put it back. Is there any working going on to upgrade?

Cheers!

**Comment by soliury** [comment]
Yes, I am trying to upgrade. When I finish I will give you a notice.
Thank you.

**Comment by mydearxym** [comment]
你用到几乎所有的组件都不支持最新版的 react-native ， 你怎么 upgrade ?

**Comment by soliury** [comment]
哈哈，其实很多都开始支持的，而且其中几个upgrade之后就用不到了

**Comment by marsprince** [comment]
是不是可以考虑做一个新版的，适应android

**Comment by soliury** [comment]
会准备做的，目前比较忙，我会腾出时间来做的

**Comment by soliury** [comment]
重构完毕，已升级到0.23.1
