### ISSUE TITLE
RctImage模块报错

### ISSUE THREAD

**Issue by pengkobe** [soliury/noder-react-native#16]
求助：在修复了modal和icons的问题之后，还出现了这个错误。
noder-react-native/node_modules/react-native/Libraries/Image/RCTDownloadTaskWrapper.m:65:49: Null passed to a callee that requires a non-null argument

**Comment by soliury** [comment]
你的react native版本是多少？目前只支持0.8.0

**Comment by walter211** [comment]
@soliury 啥时候更新呀~

xocde升到7以后，直接rn也升了，蛋似各种报错哦~

**Comment by soliury** [comment]
最近有点小忙，过后会升级的，升级确实很多麻烦，而且升级过后很多模块得弃用，比如modal和keymapevent模块，而且还有各种问题

**Comment by soliury** [comment]
重构完毕，close
