### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by dlutwuwei** [soliury/noder-react-native#17]
clang: error: no such file or directory: 'react-native/noder-react-native/node_modules/react-native-modal/node_modules/react-native-blur/RNBlur/BlurViewManager.m'
clang: error: no input files

我看了一下 react-native-modal确实不包含react-native-blur啊

**Comment by soliury** [comment]
得重新安装

**Comment by dlutwuwei** [comment]
重新npm install 么？

**Comment by soliury** [comment]
是的

**Comment by miaoyinjun** [comment]
npm install也不行啊

**Comment by lufengjian049** [comment]
重新 install  还是出现同样的错误

**Comment by soliury** [comment]
查一查你们的包得依赖

```
npm outdate
```

**Comment by hugojing** [comment]
我也是。。

**Comment by soliury** [comment]
我擦，咋个都是编译错误啊

**Comment by ah-kevin** [comment]
同上

**Comment by kuake** [comment]
重来多次不行
npm outdate

Package                  Current       Wanted  Latest  Location
query-string               2.4.2        2.4.2   3.0.0  query-string
react-native               0.8.0        0.8.0  0.13.2  react-native
react-native-blur          0.5.4        0.5.4   0.7.5  react-native-blur
react-native-button        1.2.0        1.2.0   1.2.1  react-native-button
react-native-camera        0.3.3        0.3.3   0.3.8  react-native-camera
react-native-icons         0.3.6        0.3.6   0.6.0  react-native-icons
react-native-modal         0.3.8        0.3.8  0.3.10  react-native-modal
redux                1.0.0-alpha  1.0.0-alpha   3.0.4  redux

**Comment by passol1988** [comment]
同上
Package                               Current       Wanted       Latest  Location
query-string                            2.4.2        2.4.2        3.0.0  noder
react-native                            0.8.0        0.8.0       0.14.2  noder
react-native-blur                       0.5.4        0.5.4        0.7.6  noder
react-native-button                     1.2.0        1.2.0        1.3.1  noder
react-native-camera                     0.3.3        0.3.3        0.3.8  noder
react-native-icons                      0.3.6        0.3.6        0.6.3  noder
react-native-modal                      0.3.8        0.3.8       0.3.10  noder
react-native-scrollable-tab-view       0.1.10       0.1.10  0.2.2-alpha  noder
redux                             1.0.0-alpha  1.0.0-alpha        3.0.4  noder

环境是OSX10.10.4+Xcode6.3.2

**Comment by SunLn** [comment]
Package                               Current       Wanted  Latest  Location
query-string                            2.4.2        2.4.2   3.0.0  query-string
react-native                            0.8.0        0.8.0  0.16.0  react-native
react-native-blur                       0.5.4        0.5.4   0.7.6  react-native-blur
react-native-button                     1.2.0        1.2.0   1.3.1  react-native-button
react-native-camera                     0.3.3        0.3.3   0.3.8  react-native-camera
react-native-icons                      0.3.6        0.3.6   0.7.0  react-native-icons
react-native-modal                      0.3.8        0.3.8  0.3.10  react-native-modal
react-native-scrollable-tab-view       0.1.10       0.1.10   0.3.2  react-native-scrollable-tab-view
redux                             1.0.0-alpha  1.0.0-alpha   3.0.5  redux

我的也是跑不起来。

node v4.0.0   +  OS 10.10.5 + Xcode 7.2

**Comment by leijing7** [comment]
编译错误
clang: error: no such file or directory: '/Users/xxxx/Data/tmp/noder-react-native/node_modules/react-native-modal/node_modules/react-native-overlay/RNOverlayManager.m'
clang: error: no input files

**Comment by soliury** [comment]
统一回复，目前正在重构，在这个分支： https://github.com/soliury/noder-react-native/tree/v1.0.0-alpha2

**Comment by soliury** [comment]
目前重构完毕，安卓也已经发布，目前项目编译时可行的
