### ISSUE TITLE
你好，我想问下项目编译好了，但是在模拟器上一片空白啊

### ISSUE THREAD

**Issue by yanaginagi** [soliury/noder-react-native#22]
![image](https://cloud.githubusercontent.com/assets/12086907/13308278/e53b437c-dbac-11e5-8fbe-df83591b7479.png)
点左下角登陆发现要扫描二维码登陆，但是在模拟器上怎么扫描啊？

**Comment by yanaginagi** [comment]
![image](https://cloud.githubusercontent.com/assets/12086907/13308322/34aaf3d0-dbad-11e5-98bc-5ae673a2e0ec.png)

**Comment by soliury** [comment]
这个确实没办法，这个android模拟器上是可以扫描的，而且还有，把home里面的componentDidMount的东西uncomment就好了，附带一句，这个项目重构还没有完成

**Comment by 201528013329008** [comment]
@soliury componentDidMount在哪个文件夹下面，之前弹出过是否允许使用摄像头，我一不小心给拒绝了，求问解决方法 谢谢

**Comment by footearth** [comment]
用安卓模拟器 扫了 二维码 也没有数据，是 数据拉取 还没有 重构好么？

**Comment by soliury** [comment]
android是可以的，我在我模拟器上测试时可以的，

**Comment by soliury** [comment]
你debug看看一下吧

**Comment by NexusLee** [comment]
确实是没有数据，是要配置的吗？

**Comment by soliury** [comment]
是需要配置，uncomment掉`componentDidMount`的的东西
