### ISSUE TITLE
IOS。。。。。  Android 弄啥咧

### ISSUE THREAD

**Issue by roking99** [soliury/noder-react-native#3]

**Comment by soliury** [comment]
哈哈，等facebook开源安卓版本，这个也会跟进的

**Comment by roking99** [comment]
刚学android，微博看到你发的这个。还以为是android版本的。至于你说Facebook开源神马的 跟这个有啥关系我就不知道啦。

**Comment by soliury** [comment]
嗦嘎，facebook大概十月会发布这个react-native的安卓版本。

**Comment by roking99** [comment]
唉。本来想成为一个ioser的 奈何穷B搞不起mac啊。有类似的 或者 有意思的android ui项目推荐下？
谢

**Comment by soliury** [comment]
这个。。不太了解安卓。。。。你可以去百度或者谷歌一下嘛

**Comment by roking99** [comment]
哦了个key，watching这个项目。等你说的Facebook开源了，我在捣鼓吧。

**Comment by soliury** [comment]
值得一等，不过估计坑比较多。哈哈
