### ISSUE TITLE
Android客户端最新版 v1.0.0 设置中点击清除缓存会闪退

### ISSUE THREAD

**Issue by TakWolf** [soliury/noder-react-native#31]
手机型号是：new noto x 2014 - XT1085 , Android 5.1

**Comment by soliury** [comment]
我擦，应该是个bug，我稍后查看一下

**Comment by TakWolf** [comment]
https://github.com/soliury/noder-react-native/pull/34

**Comment by TakWolf** [comment]
app这个目录中的代码是打算废弃的吗？源码都迁移到src中了吗？

**Comment by soliury** [comment]
merged。

app这个目录打算废弃，但是目前不打算删除，等正式上线后删除
