### ISSUE TITLE
执行 npm start 会出现错误

### ISSUE THREAD

**Issue by TakWolf** [soliury/noder-react-native#32]
执行 npm start 会出现如下错误：
![image](https://cloud.githubusercontent.com/assets/6064962/14582894/2212c580-0444-11e6-9a5d-98908a779764.png)

全局环境中存在 react-native-cli
![image](https://cloud.githubusercontent.com/assets/6064962/14582899/4ca563de-0444-11e6-8c06-2c9bb6fb2f9c.png)
底下的内个 react-native: 0.23.1 貌似是项目自带的react-native依赖

因为我在全局环境中运行时这样的：
![image](https://cloud.githubusercontent.com/assets/6064962/14582909/8af8775c-0444-11e6-9a96-abf520252785.png)

去搜了一下发现是一个普遍的问题：
http://stackoverflow.com/questions/33908314/packager-wont-start
猜测原因是执行npm start会造成react-native路径错误
![image](https://cloud.githubusercontent.com/assets/6064962/14582918/eb0a2bd6-0444-11e6-863b-23ddabc71982.png)

目前的解决方案是直接运行 react-native start 或者 直接运行 react-native run-android 可以正常启动。

![image](https://cloud.githubusercontent.com/assets/6064962/14582927/2e0959b6-0445-11e6-9880-5f1a87948294.png)

**Comment by soliury** [comment]
解决办法是在该项目下安装react-native-cli

**Comment by TakWolf** [comment]
@soliury 
我在局部环境下安装了react-native-cli，还是报这个错误
难道我要把全局环境中的cli删除吗？

**Comment by TakWolf** [comment]
这个问题已解决，start脚本应该配置为：

"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  }

**Comment by soliury** [comment]
ok, 我改一改
