### ISSUE TITLE
android项目中 react-native-vibration 这个模块无法引用

### ISSUE THREAD

**Issue by TakWolf** [soliury/noder-react-native#33]
不太清楚是什么原因，貌似是模块本身的问题

分支为 1.0.0-alpha2

![image](https://cloud.githubusercontent.com/assets/6064962/14583191/c422b8fa-044c-11e6-9a26-812bf326fdd7.png)

我现在只能暂时将这个模块注释掉来运行

**Comment by TakWolf** [comment]
解决了，少个package引用

https://github.com/soliury/noder-react-native/pull/34

**Comment by soliury** [comment]
这个模块本身就不用，因为我之前引用了，估计是有地方忘记删除了
