### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by yangqiong** [soliury/noder-react-native#35]
克隆下来后编译失败，提示 'RCTRootView.h' file not found.

**Comment by soliury** [comment]
请使用`v1.0.0-alpha2`分支，还有能贴详细的错误信息么？这种错误信息一般都是按照包时没安装好，重新install吧，还有你的环境是什么的环境？
例如：mac系统版本、xcode版本、npm版本、node版本、npm的源是属于什么源（淘宝or美团or npmjs.org）

**Comment by TakWolf** [comment]
拉去到最新分之后，iOS出现构建错误

![image](https://cloud.githubusercontent.com/assets/6064962/14643849/92c5654a-0682-11e6-9b52-bbabe97440ab.png)

![image](https://cloud.githubusercontent.com/assets/6064962/14643870/a5558b72-0682-11e6-8fca-63bb31546c4c.png)

在xcode中删除后构建正常

**Comment by yangqiong** [comment]
@TakWolf 谢谢，删除main.jsbundle文件后，重新构建成功

**Comment by soliury** [comment]
目前这个问题我还木有很好的解决办法额。。。

**Comment by soliury** [comment]
每次有人clone下来，都得解决main.jsbundle问题。。

**Comment by alsotang** [comment]
main.jsbundle问题是个啥问题？

2016-04-26 10:51 GMT+08:00 soliury <notifications@github.com>:

**Comment by soliury** [comment]
就是ios工程项目中添加了main.jsbundle，然而实际这个文件不存在，我把main.jsbundle删除了，现在应该ok了
