### ISSUE TITLE
查看回复，需要再次点击，有点不太习惯

### ISSUE THREAD

**Issue by alsotang** [soliury/noder-react-native#38]
这个。。每次都要点评论确实很烦啊。。。

**Comment by TakWolf** [comment]
这么做估计是妥协的办法，否则就要在ListView顶部添加一个header

**Comment by soliury** [comment]
查看回复需要再次点击。。。这是指什么场景下啊

**Comment by TakWolf** [comment]
@soliury 这个指的应该是，评论不在话题正文下面，而需要进入一个单独的页面查看

**Comment by soliury** [comment]
这个在app里场景很正常啊，因为如果放在下面，反而不好定位到评论上，翻页是最好的

**Comment by alsotang** [comment]
作为论坛形式的app，正文跟评论在同一页显示才算是正常交互吧？

2016-05-05 23:48 GMT+08:00 soliury <notifications@github.com>:

**Comment by soliury** [comment]
这个但是，不好做啊，目前稍微有点麻烦。。。。

**Comment by alsotang** [comment]
不好做就不做嘛。还是要说出来的哈哈

2016-05-06 14:17 GMT+08:00 soliury <notifications@github.com>:

**Comment by soliury** [comment]
哈哈，那这个关了咯
