### ISSUE TITLE
Android的发行包希望可以托管在FIR上

### ISSUE THREAD

**Issue by TakWolf** [soliury/noder-react-native#39]
![image](https://cloud.githubusercontent.com/assets/6064962/15043873/4a86113e-1303-11e6-822e-86005262301a.png)

![image](https://cloud.githubusercontent.com/assets/6064962/15043916/9bb76526-1303-11e6-9a3c-cc3f74b51d94.png)

很多时候都打不开，蒲公英从年后开始就一直出问题

**Comment by alsotang** [comment]
话说 fir 和这个 pgyer 哪个更好？我之前一直是听说 fir 的。。。

@soliury 你的用户名我每次都记不住 T T，每次 at 你的时候都翻来覆去找你用户名。。。能告诉我怎么读吗？

**Comment by soliury** [comment]
我尝试过在fir上，但是fir上有个问题，就是ios不能打包，打包一直失败，貌似是rn的问题，还有他们打包工具的问题，我再看看，我今天正在研究这个问题

**Comment by alsotang** [comment]
fir 有没有人在 github 上啊，拉个人进来聊聊 😄

2016-05-05 23:31 GMT+08:00 soliury <notifications@github.com>:

**Comment by soliury** [comment]
不知道啊

**Comment by TakWolf** [comment]
@soliury 1.0.5版

Home加载更多的limit给的太小了，滑动起来有点不爽啊

**Comment by baurine** [comment]
@TakWolf @soliury fir.im 的 iOS 打包如果想分发给所有人使用，是需要自己提供企业证书的。
