### ISSUE TITLE
Code Style 没有说清楚，建议添加 .eslintrc 文件

### ISSUE THREAD

**Issue by skyline75489** [soliury/noder-react-native#4]
RT

**Comment by soliury** [comment]
好的，我把.editorconfig添加上了，我再看看如何写一个.eslintrc

**Comment by skyline75489** [comment]
.eslintrc 可以直接用 react-native 主仓库的 https://github.com/facebook/react-native/blob/master/.eslintrc ，这个基本上也是大家都在遵守的一个 linter 规则

**Comment by soliury** [comment]
好的，已添加。
谢谢哇
