### ISSUE TITLE
Android导航到最后一步，按物理返回键，无法退出APP

### ISSUE THREAD

**Issue by TakWolf** [soliury/noder-react-native#41]
在Home页面的时候，物理返回键无法退出APP

**Comment by alsotang** [comment]
@soliury 你有安卓手机调试吗？^_^

2016-05-05 22:26 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by soliury** [comment]
有啊，公司有

**Comment by soliury** [comment]
fixed
