### ISSUE TITLE
安卓5.0.2 noder1.03打开有图片的帖子闪退

### ISSUE THREAD

**Issue by zouzhenxing** [soliury/noder-react-native#43]
安卓5.0.2 noder1.03打开有图片的帖子闪退
![1](https://cloud.githubusercontent.com/assets/16457664/15101473/dba14310-15c3-11e6-90a2-41c62faa5648.jpg)

**Comment by TakWolf** [comment]
@alsotang  
不只是5.0，基本上所有Android系统版本都崩溃。iOS没问题。

目测这个提交有问题。
https://github.com/soliury/noder-react-native/commit/6da899e3720616419083fa7952c23d714bb80e21

没有过滤gif之前，gif在两个平台都是可用的。感觉之前的频繁崩溃跟gif没关系，更像是数据存储的问题

**Comment by soliury** [comment]
找到问题了，Image.getSize在0.24.0中貌似木有实现。。。。0.25.0才有。。。

**Comment by soliury** [comment]
Fixed in : https://github.com/soliury/noder-react-native/commit/e63c833e98e9ea8abcc42cacd2ee6c00cbd389b3
