### ISSUE TITLE
无法启动android

### ISSUE THREAD

**Issue by nouh** [soliury/noder-react-native#48]
运行 `react-native run-android` 的时候build failed

**Comment by soliury** [comment]
具体什么错误，能贴出来么

**Comment by TakWolf** [comment]
克隆项目之后，android的项目需要初始化，即在Android目录环境之下，local.properties文件中添加你的Android sdk路径，像这样：

`sdk.dir=/Users/takwolf/Library/Android/sdk`

如果你有Android studio，导入项目之后会自动添加

之后可以正常构建

**Comment by nouh** [comment]
Error:(104, 0) Could not find property 'MYAPP_RELEASE_STORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.

**Comment by TakWolf** [comment]
@nouh 

参考这个https://github.com/soliury/noder-react-native/issues/44
