### ISSUE TITLE
andriod 下”扫码登陆” 程序立马停止

### ISSUE THREAD

**Issue by rendongsc** [soliury/noder-react-native#50]
andriod 版本：4.4，权限管理已开启： 调用摄像头。
刚刚装好后运行时正常的！

**Comment by soliury** [comment]
这个bug有点奇怪额，不太能确定是什么错误导致的，你得noder版本是多少？

**Comment by rendongsc** [comment]
昨天从https://www.pgyer.com/noder下载安装的。
 出现这个问题，我重启手机还说一样会自动停止。
 卸载重装后目前是正常的。

**Comment by soliury** [comment]
其实就是第一版的bug，后来修复了，但是你得下载过后联通wiki 几分钟后，重新启动应用就会换成新版本，
