### ISSUE TITLE
架构思考？

### ISSUE THREAD

**Issue by rendongsc** [soliury/noder-react-native#52]
reducers里除了业务的还有UI的，比如user.js和userUI.js，感觉有点冗余了。
UI里的主要目的是捕获Action的状态，如果统一在Actions里提供...ing和...ed，是不是代码更清晰了？
改进后这个插件 minPendingTime.js也就不需要了。

**Comment by soliury** [comment]
如何在action中添加..ing和...ed，好奇。。。。？

当初加UI到reducer里其实是为了方便，把reducer分成两类，一类是ui 状态，一类是数据，从文件角度来说，确实冗余了，但是从开发角度来说，其实这个效率蛮高的
