### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yuu2lee4** [soliury/noder-react-native#53]
上面的tab设计成可左右滑动的
然后发帖应该是比消息更常用的功能吧  建议把发帖放在外面

**Comment by alsotang** [comment]
发帖比未读消息更常用？这特么是灌水玩家吧。。。

2016-06-17 22:10 GMT+08:00 yuri <notifications@github.com>:

**Comment by soliury** [comment]
对啊，我也想说，发帖在mobile上明显不常用啊

**Comment by yuu2lee4** [comment]
就算没有比未读消息常用 放在用户信息里面也很奇怪吧  发个帖  还要加载一堆个人信息乱七八杂的

**Comment by soliury** [comment]
这个还好吧，本身这个不是常用功能，但是又必须要有，放个人信息里很正常啊

**Comment by walter211** [comment]
大神，你的代码写的这么风骚，求加点注释

**Comment by soliury** [comment]
@walter211 加什么类型的注释啊，哪些地方需要加注释啊？你可以指出一些，我有目的的加吧

**Comment by tomoya92** [comment]
我再加两个建议

1. 到详情页手势往左滑自动进入评论列表
2. 评论列表我觉得放在详情下面比较习惯

吐个槽，评论列表为啥是倒序的呀！网站是正序，其它app都是正序，就noder倒序好不习惯啊😂

**Comment by walter211** [comment]
connectComponent.js的封装代码里面，mergeProps和mapDispatchToProps哪里来滴？

**Comment by soliury** [comment]
@walter211 reduder里的，你去看看接口文档，有描述滴

**Comment by walter211** [comment]
@soliury 官方说container尽量控制数量，即是绑定redux的组件越少越好，但你的Router好像把所有的页面都connect了？

**Comment by soliury** [comment]
对滴，但是对于这个app来说，这点container根本不算啥，而且也不会遇到性能问题，这才多少个container啊

**Comment by walter211** [comment]
@soliury 恩恩，另外我看你用了redux-actions，但是没有用handleAction是为啥，只是在reducer里面按照flux的方式处理里action。
还有引用pure-render-mixin的方式有点奇怪，是因为之前没有改么，好像react组件里面有，不需要放到依赖配置里？

**Comment by soliury** [comment]
* handleAction没必要用，所以没有用
* pure-render-mixin已经从react里移除了，注意看文档

**Comment by soliury** [comment]
https://facebook.github.io/react/docs/pure-render-mixin.html
