### ISSUE TITLE
[Upgrade to 0.28]NotFoundError: Cannot find entry file global code@http://localhost:8081/index.ios.js

### ISSUE THREAD

**Issue by stonewen** [soliury/noder-react-native#56]
`NotFoundError: Cannot find entry file global code@http://localhost:8081/index.ios.js in any of the roots: ["/Users/projects/noder-react-native"]
    at DependencyGraph._getAbsolutePath (/Users/projects/noder-react-native/node_modules/node-haste/lib/index.js:288:13)
    at /Users/projects/noder-react-native/node_modules/node-haste/lib/index.js:226:30
    at process._tickCallback (node.js:369:9)`

**Comment by soliury** [comment]
需要拉最新代码，然后删除`node_modules`，然后重新安装

**Comment by stonewen** [comment]
@soliury 还是会报错  
 删除了node_modules并npm cache clean，重新安装后仍然报错

**Comment by TakWolf** [comment]
iOS项目运行前， 输入 gulp replace 修改终端ip地址

**Comment by stonewen** [comment]
@TakWolf  改成我的终端ip地址也不行
[http://stackoverflow.com/questions/37999468/entry-file-error-in-react-native-from-packager/38044411](http://stackoverflow.com/questions/37999468/entry-file-error-in-react-native-from-packager/38044411)
[https://github.com/facebook/react-native/issues/8449](https://github.com/facebook/react-native/issues/8449)
查了一下也没找到解决办法，你们的都没问题？

**Comment by TakWolf** [comment]
你是在运行的时候报错的吗？
http://localhost:8081/index.ios.js  指的就是根目录下面的 ios入口文件，根据提示来看感觉就是id的问题啊

**Comment by TakWolf** [comment]
看了一下，貌似是 react-native 升级出现的问题

**Comment by iacxin** [comment]
一样的问题。怎么解决？

**Comment by iacxin** [comment]
react-native-cli: 1.0.0
react-native: 0.28.0

**Comment by soliury** [comment]
node什么版本，npm什么版本，然后还有npm源是什么？

**Comment by stonewen** [comment]
@soliury    node  4.4.5   npm 3.9.5  npm源是官方

**Comment by iacxin** [comment]
node 6.2.1
npm 3.9.3

**Comment by walter211** [comment]
我也报错了
node 5.3.0
npm 3.3.12

**Comment by soliury** [comment]
我回家看看，最近公司实在是太忙了。。。不好意思，这回复的有点晚

**Comment by flyskywhy** [comment]
@stonewen @TakWolf @iacxin @walter211 ，最新版已经支持 Android iOS Web 三个平台的编译和运行了 😄
