### ISSUE TITLE
框架移植后报错

### ISSUE THREAD

**Issue by walter211** [soliury/noder-react-native#57]
把工程的框架代码用到另一个项目报错了，
另外问下异常事件抛出的位置一般是在service还是在action or View层处理？
我使用了redux-actions绑定actioncreator之后并没有执行resolved，求解

2016-06-30 23:45:21.189 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
Actions may not have an undefined "type" property. Have you misspelled a constant?
dispatch@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:77022:16
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:95495:12
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:95114:5
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:95486:12
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:95092:38
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:77899:5
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:77876:12
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:77433:16
rejected@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:111509:3409
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:95096:25
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:77945:12
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:77876:12
dispatch@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:77522:17
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:77930:32
tryCallOne@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:24227:10
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:24313:19
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:5872:18
callTimer@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:5656:9
callImmediatesPass@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:5714:28
callImmediates@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:5729:43
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:4502:57
guard@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:4412:3
__callImmediates@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:4502:6
http://localhost:9381/index.ios.bundle?platform=ios&dev=true:4462:24
guard@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:4412:3
callFunctionReturnFlushedQueue@http://localhost:9381/index.ios.bundle?platform=ios&dev=true:4460:6
callFunctionReturnFlushedQueue@[native code]

**Comment by soliury** [comment]
能直接贴代码么
