### ISSUE TITLE
iOS上运行报错

### ISSUE THREAD

**Issue by mybdgw** [soliury/noder-react-native#59]
Unable to resolve module markdown from /Users/zhangxl/Desktop/GIT/noder-react-native/src/actions/topic.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/markdown and its parent directories

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

**Comment by flyskywhy** [comment]
@mybdgw , noder now support RN 0.51.0, and support Android iOS Web this three platform, maybe you should try it again 😄
