### ISSUE TITLE
iOS下诡异报错

### ISSUE THREAD

**Issue by krisoul** [soliury/noder-react-native#61]
ios下报错：
![](http://ww4.sinaimg.cn/large/6df1da21gw1f6fqq3u8w3j20dc0lhade.jpg)
这个错没看懂，咋整？

**Comment by soliury** [comment]
我也没看懂。。。。。

**Comment by TakWolf** [comment]
怎么出现的？

**Comment by JackLiu1002** [comment]
同样出现这个问题，有人解决了么？

**Comment by flyskywhy** [comment]
@krisoul ， noder 最新版已经支持 RN 0.51.0，以及支持 Android iOS Web 三个平台的编译和运行了 😄
