### ISSUE TITLE
git clone代码下来，npm install出错。有没有什么建议啊。能不能在代码库里面加node_modules

### ISSUE THREAD

**Issue by linyouhappy** [soliury/noder-react-native#66]
node版本已经用nvm切换到6.x以上了。
bogon:noder-react-native linyou$ npm install
npm ERR! tar.unpack unzip error /var/folders/27/ky3kk9813cjb7zvy52028t_c0000gn/T/npm-15275-5752dd68/registry.npmjs.org/xregexp/-/xregexp-3.1.1.tgz
npm ERR! tar.unpack untar error /var/folders/27/ky3kk9813cjb7zvy52028t_c0000gn/T/npm-15275-5752dd68/registry.npmjs.org/xregexp/-/xregexp-3.1.1.tgz

然后一堆这种错误。
npm ERR! fetch failed http://r.npm.sankuai.com/babel-core/download/babel-core-6.11.4.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80
npm ERR! fetch failed http://r.npm.sankuai.com/babel-helper-remap-async-to-generator/download/babel-helper-remap-async-to-generator-6.11.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80
npm ERR! fetch failed http://r.npm.sankuai.com/babel-helper-define-map/download/babel-helper-define-map-6.9.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80
npm ERR! fetch failed http://r.npm.sankuai.com/babel-helper-regex/download/babel-helper-regex-6.9.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80
npm ERR! fetch failed http://r.npm.sankuai.com/babel-generator/download/babel-generator-6.11.4.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80

能不能在代码库里面加node_modules，node的版本太多，各种版本不容易兼容。希望也上传node_modules吧。不然npm install出错，没法玩乐。

**Comment by linyouhappy** [comment]
感觉还是不要迷信npm install这套了。不然，只要有一个module出问题，第三个人下载下来，就跑不动了。谢谢啦。

**Comment by TakWolf** [comment]
你这是网络问题吧

**Comment by linyouhappy** [comment]
中国大陆需要科学上网啊。没有找到科学的方法，getlantern也没用。希望可以上传node_modules的文件夹吧。

**Comment by TakWolf** [comment]
http://npm.taobao.org/

**Comment by soliury** [comment]
@TakWolf 已经回答了问题了

**Comment by linyouhappy** [comment]
为什么上传node_modules这么难呢？
我的配置：
bogon:noder-react-native linyou$ npm config ls
; cli configs
user-agent = "npm/3.8.9 node/v6.2.0 darwin x64"

; userconfig /Users/linyou/.npmrc
registry = "https://registry.npm.taobao.org/"

; node bin location = /Users/linyou/.nvm/versions/node/v6.2.0/bin/node
; cwd = /Users/linyou/Developer/forfun/noder-react-native
; HOME = /Users/linyou
; "npm config ls -l" to show all defaults.
还是不行啊

**Comment by linyouhappy** [comment]
期待上传node_modules吧。这样子，保证不会出错了。

**Comment by soliury** [comment]
不会上传node_modules的，还请翻墙试试

**Comment by TakWolf** [comment]
问题迁移：https://github.com/soliury/noder-react-native/issues/68
