### ISSUE TITLE
npm install失败，跪求提供node_modules目录

### ISSUE THREAD

**Issue by linyouhappy** [soliury/noder-react-native#67]

**Comment by linyouhappy** [comment]
看了你们做的项目，还是感觉xamarin好，最起码有ui编辑器可以使用。

**Comment by TakWolf** [comment]
node_modules上传不实际，会有诸多问题，例如：npm2 跟 npm3 包管理方式不兼容，windows下路径过长

个人亲测淘宝源没问题，请先确定你的情况是不是真的是网络问题？
如果确定是网络问题，那么请寻找网络解决方案，这个锅npm不背

**Comment by TakWolf** [comment]
跨平台的优秀的APP构建方案有很多，xamarin也好，cordova也好，Qt也好，每个都有自己的市场目标，选择合适自己的就好，没必要比较。欢迎交流技术

**Comment by linyouhappy** [comment]
node_modules上传没关系吧。下载的人，发现有问题，可以删除node_modules啊，自己install啊。下载安装的人一般，会选择你们的版本啊。

**Comment by linyouhappy** [comment]
上传node_modules，多了一个被选项，跑项目的时候，多了一个选择。

**Comment by linyouhappy** [comment]
现在node的版本太多，然后ES新标准又众多变化了。变成了项目选择node和npm版本。而不是任意一个node可以跑各种各样的项目。

**Comment by linyouhappy** [comment]
你们使用npm3版本，作为下载你们下面的人，肯定选择npm3版本吧。不会选择npm2吧。毕竟搞node的人，被它的各个版本整怕了。

**Comment by TakWolf** [comment]
你确定你的问题真的是网络问题吗？其他node项目，依赖可以安装成功吗？

**Comment by linyouhappy** [comment]
其他项目都可以啊。直接npm install react-native都可以。本地通过nvm安装了各种版本了。

**Comment by TakWolf** [comment]
目测不是网络问题，请先查清楚错误的具体原因

**Comment by TakWolf** [comment]
package.json本身就配置为淘宝源，也没有使用其他厂库依赖，目测不是网络问题。
我之前判断为网络问题，仅仅是因为看到了fatch error而已

**Comment by alsotang** [comment]
node_modules 肯定不会上传的，没有项目这么干。

2016-08-21 20:02 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by linyouhappy** [comment]
npm install --registry=http://registry.npm.taobao.org/
npm WARN package.json noder@1.0.5 No repository field.
npm WARN package.json noder@1.0.5 No license field.
npm WARN package.json Dependency 'react-native-cli' exists in both dependencies and devDependencies, using 'react-native-cli@^1.0.0' from dependencies
npm ERR! fetch failed http://r.npm.sankuai.com/babel-helper-regex/download/babel-helper-regex-6.9.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80
npm ERR! fetch failed http://r.npm.sankuai.com/babel-helper-remap-async-to-generator/download/babel-helper-remap-async-to-generator-6.11.2.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80
npm ERR! fetch failed http://r.npm.sankuai.com/babel-core/download/babel-core-6.11.4.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80
npm ERR! fetch failed http://r.npm.sankuai.com/babel-helper-define-map/download/babel-helper-define-map-6.9.0.tgz

**Comment by linyouhappy** [comment]
谁去搞死宫匪

**Comment by linyouhappy** [comment]
为了跑起你们源代码，老子天天npm install。天天一堆错误。什么狗屎开源啊。上传个node_modules，都不肯。

**Comment by TakWolf** [comment]
我靠，代码作者是该你的还是欠你的了？人家愿意开源，又没求着你来跑，还是说你给钱了？

我就想问，为啥我们跑就没问题啊？你tm还有理了

**Comment by TakWolf** [comment]
解决方案：

https://github.com/soliury/noder-react-native/issues/68

**Comment by tomoya92** [comment]
这货还把他的回复记录都删了。。
![image](https://cloud.githubusercontent.com/assets/6915570/17933788/f9cd5e2c-6a47-11e6-9cb7-b2c7757379fe.png)

**Comment by soliury** [comment]
哎，懒得理，关了
