### ISSUE TITLE
npm install 报错：getaddrinfo ENOTFOUND r.npm.sankuai.com r.npm.sankuai.com:80

### ISSUE THREAD

**Issue by TakWolf** [soliury/noder-react-native#68]
@soliury 

现在部分依赖包路径会强制走 r.npm.sankuai.com ，查了一下，貌似是美团的私有镜像

判定是 npm-shrinkwrap.json 这个文件引起的（我第一次知道还有这种用法），删除之后可以正常从公共仓库添加依赖

这个问题解决一下吧，有人已经构建失败了

另外求科普 npm-shrinkwrap.json 的原理

**Comment by TakWolf** [comment]
npm-shrinkwrap.json 的原理：

http://www.tuicool.com/articles/EBVNV37

**Comment by soliury** [comment]
这个啊，哦哦，那是我的问题，我稍后改一改

**Comment by soliury** [comment]
已修复，不知道为啥会出现这样的情况，我安装时明明用的是淘宝的源，然后npm shrinkwrap出来就是sankuai的源
