### ISSUE TITLE
 npm run checkversion error

### ISSUE THREAD

**Issue by linyouhappy** [soliury/noder-react-native#70]
> noder@1.0.5 postinstall /Users/linyou/Developer/forfun/noder-react-native
> npm run checkversion
>  noder@1.0.5 checkversion /Users/linyou/Developer/forfun/noder-react-native
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/linyou/Developer/forfun/noder-react-native/node_modules/fbjs-scripts/node/check-dev-engines.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "checkversion"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! noder@1.0.5 checkversion: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noder@1.0.5 checkversion script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
npm ERR! This is most likely a problem with the noder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs noder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls noder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/linyou/Developer/forfun/noder-react-native/npm-debug.log

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! noder@1.0.5 postinstall: `npm run checkversion`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noder@1.0.5 postinstall script 'npm run checkversion'.
npm ERR! This is most likely a problem with the noder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run checkversion
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs noder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls noder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/linyou/Developer/forfun/noder-react-native/npm-debug.log

**Comment by TakWolf** [comment]
https://github.com/soliury/noder-react-native/blob/v1.1.x/package.json#L78

```

  "devEngines": {
    "node": ">= 4.x",
    "npm": ">= 3.x"
  },

```

**Comment by linyouhappy** [comment]
用node6.0的npm可以跑，iOS和安卓均跑通

**Comment by linyouhappy** [comment]
昨晚半夜刷安卓真机，闪退了。未能在真机上跑通

**Comment by flyskywhy** [comment]
@linyouhappy ， noder 最新版已经支持 RN 0.51.0，以及支持 Android iOS Web 三个平台的编译和运行了 😄
