### ISSUE TITLE
ERROR in Path must be a string. Received undefined

### ISSUE THREAD

**Issue by linyouhappy** [soliury/noder-react-native#71]
WARNING in ./~/react-native-html-render/lib/htmlparser2.js
Critical dependencies:
1:755-762 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-native-html-render/lib/htmlparser2.js 1:755-762

ERROR in Path must be a string. Received undefined
webpack: bundle is now VALID.

HuangdeMac-mini:~ huang$ node -v
v6.4.0
HuangdeMac-mini:~ huang$ npm -v
3.10.3

**Comment by linyouhappy** [comment]
导出的noder-react-native/web/output/index.html文件，只有这一行TypeError: Path must be a string. Received undefined

**Comment by wk1017553772** [comment]
我也碰到了同样的问题，网页上无法访问
<img width="1145" alt="2016-09-17 2 25 34" src="https://cloud.githubusercontent.com/assets/4082286/18606439/b462ac36-7ce2-11e6-9be5-2108d802f7e3.png">

**Comment by flyskywhy** [comment]
@linyouhappy @wk1017553772 ，看起来 https://github.com/taobaofed/react-web/issues/136 解决了这个问题，说是要用 node 5.x 而不能是 node 6：

    it's impossible to get it to work with the latest version of react and node 6, use NVM and run react-web start with node 5.x
