### ISSUE TITLE
怎么调试类的方法呢？

### ISSUE THREAD

**Issue by linyouhappy** [soliury/noder-react-native#73]
谷歌浏览器和atom都可以调试。但是，在类的方法，就没法设断点，有没有好的方法呢？

**Comment by linyouhappy** [comment]
ES6新标准，把简单的js，彻底推向复杂化了。无形之中加大学习门槛。

**Comment by TakWolf** [comment]
跟项目无关的问题，最好发到社区里 
https://cnodejs.org

----------------- 分割线 -----------------------

我不清楚你是怎么使用es6的，Babel的话，因为是原理是编译兼容，断点要打到编译后的源文件行才有效

**Comment by linyouhappy** [comment]
react-native run-ios启动，然后它会弹出浏览器，在浏览器可以调试，但是由于类的定义比较新，导致没法设置断点，一设置断点，断点就跑到文件底部。
atom编辑器调试，也是这种问题。谢谢啦。

**Comment by linyouhappy** [comment]
谷歌浏览器通过翻墙，升级到最新了。
