### ISSUE TITLE
[ 评论回复功能]真机测试发表或者回复评论 appcrash

### ISSUE THREAD

**Issue by EvanJin** [soliury/noder-react-native#8]
发表评论的时候，切换中文输入法，会导致app crash

**Comment by soliury** [comment]
是每一个帖子都会这样么？还是偶尔，还是固定一个帖子会出现这个问题？还有你所说的切换输入法是指什么输入法，原本是什么输入法，然后切换成什么输入法？

我用百度中文切换到本地自带的英文都没有问题

**Comment by EvanJin** [comment]
@soliury , 每个帖子都一样，我用的是IOS的自带的输入法，忘了说了，我的系统是ios7.1

**Comment by soliury** [comment]
ok，I see.

**Comment by soliury** [comment]
应该是个bug，但是我8.3没有问题，这个就有点蛋疼了。

**Comment by soliury** [comment]
你的时Iphone几？5？

**Comment by EvanJin** [comment]
@soliury, iphone 5s, 我也在看代码中，测试结果应该是你引入的那个keyboardevents模块，导致的crash

**Comment by EvanJin** [comment]
@soliury, iphone 5s, 我也在看代码中，测试结果应该是你引入的那个keyboardevents模块，导致的crash，找到原因修复，我在给你提pr

**Comment by soliury** [comment]
ok，你可以先去keyboardevents的github看看有木有类似的issue，我觉得应该有类似的bug发生过。

**Comment by soliury** [comment]
不知道现在这个问题，有木有神马进展？

**Comment by soliury** [comment]
重构完毕
