### ISSUE TITLE
Camera.checkDeviceAuthorizationStatus()报错：is not a function

### ISSUE THREAD

**Issue by dazich** [soliury/noder-react-native#85]
点扫码登录的时候报的这个错

**Comment by soliury** [comment]
应该是这个库升级了，然后这个方法被干掉了。。。。
我确实是应该更新一下这个项目了。。。

**Comment by dangyanglim** [comment]
我也是，怎么处理

**Comment by dangyanglim** [comment]
在android7.1.1上面报错了

**Comment by dangyanglim** [comment]
这个方法没有被干掉吧，我在那个库的介绍页面还可以看的到，
iOS Camera.checkDeviceAuthorizationStatus(): Promise
不过为什么只有ios？

**Comment by flyskywhy** [comment]
@dangyanglim ，最新版的 1db4fdf 和 925a10c 两个提交点修复了这儿问题 😄
