### ISSUE TITLE
项目没办法跑起来！xcode中各种头文件找不到

### ISSUE THREAD

**Issue by CoderZF** [soliury/noder-react-native#89]
![image](https://user-images.githubusercontent.com/16768001/31659936-5aff327c-b2fb-11e7-9026-a3a1d12a1356.png)
 
望作者抽个空看看！真心想研究研究这个项目。。

**Comment by CoderZF** [comment]
node 6.11.0
npm 3.10.10
Xcode 9.0 
iOS 11.0

**Comment by uinz** [comment]
@CoderZF 
应该是你的 .cache 没下载完全

这些问题一先去处理一下.
[传送门](http://vanessa.b3log.org/articles/2017/06/12/1497235254333.html)

xcode9 swift 编译版本最低是3.2了, 如果这个项目有用到老swift 的话, 你可能还需要折腾一番

**Comment by CoderZF** [comment]
@uinz 这个项目好像没有用swift啊，，，把Always Search User Paths 设置为 Yes还是一样的报错。。

**Comment by uinz** [comment]
@CoderZF 你应该是rncache 没下载完全，手动下载覆盖吧。 解压到.cache  里  ，传送门里有说

**Comment by CoderZF** [comment]
@uinz 项目中没有node_modules/react-native/third-party路劲啊；third-party这个文件夹没有，是需要新建吗？

**Comment by CoderZF** [comment]
@uinz 
![image](https://user-images.githubusercontent.com/16768001/31703785-c963725c-b3a3-11e7-9bc3-32d31f421c7f.png)

**Comment by CoderZF** [comment]
@uinz 上面图截错了，是这个但也还是没有
![image](https://user-images.githubusercontent.com/16768001/31704058-3570b1de-b3a5-11e7-9cae-6bebb07e44a6.png)

**Comment by CoderZF** [comment]
@uinz 是替换这个？
![image](https://user-images.githubusercontent.com/16768001/31704365-90a99d6c-b3a6-11e7-96e6-0e357f536b6f.png)

**Comment by soliury** [comment]
这个项目好久没有更新了，容我有空，这个星期周末看看

**Comment by CoderZF** [comment]
嗯嗯  期待期待哦。。这么好的项目跑都跑不起来，真揪心哦。




发自网易邮箱大师
在2017年10月18日 19:37，soliury 写道：

这个项目好久没有更新了，容我有空，这个星期周末看看

**Comment by flyskywhy** [comment]
@CoderZF 最新版已经支持 Android iOS Web 三个平台的编译和运行了 😄

**Comment by CoderZF** [comment]
好的 。。。大神，，辛苦了




| |
严志帆
|
|
邮箱：17301166515@163.com
|

签名由 网易邮箱大师 定制

在2017年12月31日 21:40，Li Zheng 写道：

@CoderZF 最新版已经支持 Android iOS Web 三个平台的编译和运行了 😄
