### ISSUE TITLE
[运行错误]'WebView' has no propType for native prop.....

### ISSUE THREAD

**Issue by razor1895** [soliury/noder-react-native#9]
我重装了三次，依旧报错，也许是环境问题，我的环境是 OS X El Capitan Beta4和Xcode7 beta
![bug](https://cloud.githubusercontent.com/assets/5582475/8977011/5918f5ae-36c7-11e5-92aa-31d3c619c42e.png)

**Comment by soliury** [comment]
目前我还不知道是神马原因，也有可能是编译的问题，先放着

**Comment by razor1895** [comment]
@soliury 我今晚回去试试其他react-native项目能不能在模拟器中运行成功

**Comment by soliury** [comment]
@razor1895 好的，谢谢啊。

**Comment by soliury** [comment]
对于这个问题，你能不能尝试一下重新编译oc代码试试，就是把所有的oc代码都编译一次，这个我还没有找到一个好的命令行编译的方法，你在运行的按钮右边，选择每一个依赖的库，分别comm+b编译一次

**Comment by razor1895** [comment]
@soliury 

<addr>[tid:com.facebook.React.JavaScript] 'Error: Invariant Violation: Application noder has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.\n stack: \n  runApplication  index.ios.bundle:38705\n  __callFunction  index.ios.bundle:7158\n  <unknown>       index.ios.bundle:7094\n  guard           index.ios.bundle:7047\n  <unknown>       index.ios.bundle:7094\n  <unknown>       index.ios.bundle:7091\n  perform         index.ios.bundle:6495\n  batchedUpdates  index.ios.bundle:15823\n  batchedUpdates  index.ios.bundle:5027\n  <unknown>       index.ios.bundle:7090\n  guard           index.ios.bundle:7047\n  processBatch    index.ios.bundle:7089\n URL: http://localhost:8081/index.ios.bundle\n line: 2023\n message: Invariant Violation: Application noder has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.'

**Comment by soliury** [comment]
不是，这个问题不是xcode7的问题，是依赖的库没有，就是安装不全，这个是js错误。
重新安装试试

**Comment by soliury** [comment]
咋样，这个是神马问题？有木有后续进展，能不能在这里说明一下呀，以便其他人遇到这个问题也能够解决。

**Comment by razor1895** [comment]
@soliury 昨天重新安装了一遍，依然报这个错误。今天下午去公司用同事的macbook试一试

**Comment by soliury** [comment]
pull 一下最新版试试

**Comment by razor1895** [comment]
I solved this!!!! Just update react-native to the newest version ......
= = wtf!!!

**Comment by soliury** [comment]
你是指更新到0.8.0么？

**Comment by razor1895** [comment]
@soliury 是的，更新之后就好了

**Comment by soliury** [comment]
ok，I see.
