### ISSUE TITLE
怎么打包发布android和ios呢

### ISSUE THREAD

**Issue by 95zz** [soliury/noder-react-native#96]
怎么打包发布android和ios呢

**Comment by flyskywhy** [comment]
android 请参考 [release 离线打包 ](https://github.com/flyskywhy/g/blob/master/i%E4%B8%BB%E8%A7%82%E7%9A%84%E4%BD%93%E9%AA%8C%E6%96%B9%E5%BC%8F/t%E5%BF%AB%E4%B9%90%E7%9A%84%E4%BD%93%E9%AA%8C/%E7%94%B5%E4%BF%A1/Tool/%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80/JavaScript/React%E4%BD%BF%E7%94%A8%E8%AF%A6%E8%A7%A3.md#release-离线打包) 
ios 可参考 [ReactNative项目中命令行编译iOS版的方法](https://github.com/flyskywhy/g/blob/master/i%E4%B8%BB%E8%A7%82%E7%9A%84%E4%BD%93%E9%AA%8C%E6%96%B9%E5%BC%8F/t%E5%BF%AB%E4%B9%90%E7%9A%84%E4%BD%93%E9%AA%8C/%E7%94%B5%E4%BF%A1/Tool/%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80/JavaScript/ReactNative%E9%A1%B9%E7%9B%AE%E4%B8%AD%E5%91%BD%E4%BB%A4%E8%A1%8C%E7%BC%96%E8%AF%91iOS%E7%89%88%E7%9A%84%E6%96%B9%E6%B3%95.md)

**Comment by 95zz** [comment]
好的，谢谢
