### ISSUE TITLE
还差一个问题，改为源码之后，怎么再次构建android和ios呢

### ISSUE THREAD

**Issue by 95zz** [soliury/noder-react-native#97]
还差一个问题，改为源码之后，怎么再次构建android和ios呢

**Comment by flyskywhy** [comment]
什么叫“改为源码之后”？
“怎么再次构建”啥意思？再次运行不就行了？

**Comment by 95zz** [comment]
是比如说我修改了icon,对应的android和ios文件包，使用什么命令重新生成一次。

**Comment by 95zz** [comment]
现在这个apk 打出来了，体验到了，出现了bug,
1.当点击我的扫描二维码登录的时候，发现pc端没有二维码怎么登录呢
2.退出扫描登录界面后,主页面下半部分是黑色的
