### ISSUE TITLE
请问项目如何打成apk包？

### ISSUE THREAD

**Issue by pospospos2007** [soliury/noder-react-native#98]
请问项目如何打成apk包？文档有点不清楚，为什么运行指令就可以自动安装app，不明白。。

**Comment by flyskywhy** [comment]
参见 [release-离线打包](https://github.com/flyskywhy/g/blob/master/i%E4%B8%BB%E8%A7%82%E7%9A%84%E4%BD%93%E9%AA%8C%E6%96%B9%E5%BC%8F/t%E5%BF%AB%E4%B9%90%E7%9A%84%E4%BD%93%E9%AA%8C/%E7%94%B5%E4%BF%A1/Tool/%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80/JavaScript/React%E4%BD%BF%E7%94%A8%E8%AF%A6%E8%A7%A3.md#release-离线打包)
